#include <QtCore/qcoreapplication.h>
#include <QtCore/qstring.h>
#include <QtCore/qlist.h>
#include <QtCore/qmap.h>
#include <QtCore/qobject.h>
#include <QtCore/qvariant.h>
#include <QtCore/qsettings.h>
#include <QtCore/qfile.h>
#include <QtCore/qdatetime.h>
#include <QtCore/qtimer.h>
#include <QtCore/qsize.h>
#include <QtCore/qpoint.h>
#include <QtCore/qrect.h>
#include <QtCore/qregularexpression.h>
#include <QtCore/qurl.h>
#include <QtCore/quuid.h>

// Additional includes for complete type definitions (Qt 6.11 compatibility)
#include <QtCore/qtimezone.h>
#include <QtCore/qmetaobject.h>
#include <QtCore/qline.h>
#include <QtCore/qbitarray.h>
#include <QtCore/qlocale.h>
#include <QtCore/qeasingcurve.h>
#include <QtCore/qjsonvalue.h>
#include <QtCore/qjsonobject.h>
#include <QtCore/qjsonarray.h>
#include <QtCore/qjsondocument.h>
#include <QtCore/qmargins.h>
#include <QtCore/qiodevice.h>
#include <QtCore/qcborarray.h>
#include <QtCore/qcbormap.h>
#include <QtCore/qcborvalue.h>
#include <QtCore/qproperty.h>
#include <QtCore/qabstractitemmodel.h>  // Defines QModelIndex, QPersistentModelIndex
#include <QtCore/qitemselectionmodel.h>
#include <QtCore/qidentityproxymodel.h>
#include <QtCore/qabstractproxymodel.h>
#include <QtCore/qsortfilterproxymodel.h>
#include <QtCore/qconcatenatetablesproxymodel.h>
#include <QtCore/qtransposeproxymodel.h>
